<a href="https://colab.research.google.com/github/aanjneyapankharaj/study-of-Datasets/blob/main/experiment10.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##EDA using python
##expet - 10
##study of Datasets
####Name : Ansh Srivastavaj
###PRN : 25070123015
###batch : Entc A1

In [15]:
import pandas as pd

data = {"roll_no": [101,102,103,104,105],
        "gender":["female","male","female","male","female"]
        ,"department":["computer","it","entc","mechanical","computer"],
        "CGPA":[8.2,7.5,9.1,6.8,8.7]
 }
df = pd.DataFrame(data)
df.to_csv("students.csv",index=False)
df

   roll_no  gender  department  CGPA
0      101  female    computer   8.2
1      102    male          it   7.5
2      103  female        entc   9.1
3      104    male  mechanical   6.8
4      105  female    computer   8.7

In [11]:
df.shape

(5, 4)

In [19]:
#access the informarion about Department column
df["department"]

0      computer
1            it
2          entc
3    mechanical
4      computer
Name: department, dtype: object

In [25]:
#acess infomation about prn 103
df[df['roll_no'] == 103]

   roll_no  gender department  CGPA
2      103  female       entc   9.1

In [28]:
#perfrom mean,medin and mode of the CGPA
print("Mean of CGPA is: ",df['CGPA'].mean())
print("Median of CGPA is: ",df['CGPA'].median())
print("Mode of CGPA is: ",df['CGPA'].mode())

Mean of CGPA is:  8.059999999999999
Median of CGPA is:  8.2
Mode of CGPA is:  0    6.8
1    7.5
2    8.2
3    8.7
4    9.1
Name: CGPA, dtype: float64

In [29]:
#find our data type of each column
df.dtypes

roll_no         int64
gender         object
department     object
CGPA          float64
dtype: object

In [30]:
#insert a new column
df['age'] = [20, 21, 20, 22, 21]
df

   roll_no  gender  department  CGPA  age
0      101  female    computer   8.2   20
1      102    male          it   7.5   21
2      103  female        entc   9.1   20
3      104    male  mechanical   6.8   22
4      105  female    computer   8.7   21

In [31]:
#delete gender column
df = df.drop('gender', axis=1)
df

   roll_no  department  CGPA  age
0      101    computer   8.2   20
1      102          it   7.5   21
2      103        entc   9.1   20
3      104  mechanical   6.8   22
4      105    computer   8.7   21

In [34]:
#CGPA of topper
print("CGPA of topper is: ",df['CGPA'].max())

CGPA of topper is:  9.1

In [32]:
#cgpa of prn 105
print("CGPA of PRN 105 is: ",df.loc[df['roll_no'] == 105, 'CGPA'])

CGPA of PRN 105 is:  4    8.7
Name: CGPA, dtype: float64

In [10]:
import pandas as pd
import numpy as np

df=pd.read_csv('/content/Cars93.csv')
df

,Manufacturer,Model,Type,Price,MPG.city,AirBags,Horsepower,Passengers,Rear.seat.room,Luggage.room
0,Acura,Integra,Small,15.9,25,NaN,140,5,26.5,11.0
1,Acura,Legend,Midsize,33.9,18,Driver & Passenger,200,5,30.0,15.0
2,Audi,90,Compact,29.1,20,Driver only,172,5,28.0,14.0
3,Audi,100,Midsize,37.7,19,Driver & Passenger,172,6,31.0,17.0
4,BMW,535i,Midsize,30.0,22,Driver only,208,4,27.0,13.0
...,...,...,...,...,...,...,...,...,...,...
88,Volkswagen,Eurovan,Van,19.7,17,NaN,109,7,34.0,NaN
89,Volkswagen,Passat,Compact,20.0,21,NaN,134,5,31.5,14.0
90,Volkswagen,Corrado,Sporty,23.3,18,NaN,178,4,26.0,15.0
91,Volvo,240,Compact,22.7,21,Driver only,114,5,29.5,14.0
92,Volvo,850,Midsize,26.7,20,Driver & Passenger,168,5,30.0,15.0

In [11]:
df.shape

(93, 10)

In [13]:
df.head()

,Manufacturer,Model,Type,Price,MPG.city,AirBags,Horsepower,Passengers,Rear.seat.room,Luggage.room
0,Acura,Integra,Small,15.9,25,NaN,140,5,26.5,11.0
1,Acura,Legend,Midsize,33.9,18,Driver & Passenger,200,5,30.0,15.0
2,Audi,90,Compact,29.1,20,Driver only,172,5,28.0,14.0
3,Audi,100,Midsize,37.7,19,Driver & Passenger,172,6,31.0,17.0
4,BMW,535i,Midsize,30.0,22,Driver only,208,4,27.0,13.0

In [14]:
df.tail()

,Manufacturer,Model,Type,Price,MPG.city,AirBags,Horsepower,Passengers,Rear.seat.room,Luggage.room
88,Volkswagen,Eurovan,Van,19.7,17,NaN,109,7,34.0,NaN
89,Volkswagen,Passat,Compact,20.0,21,NaN,134,5,31.5,14.0
90,Volkswagen,Corrado,Sporty,23.3,18,NaN,178,4,26.0,15.0
91,Volvo,240,Compact,22.7,21,Driver only,114,5,29.5,14.0
92,Volvo,850,Midsize,26.7,20,Driver & Passenger,168,5,30.0,15.0